name: Run test suite and calculate coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - doc.go
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - doc.go
      - LICENSE
      - README.md
  schedule:
    - cron: '0 15 * * 1' # Every Monday @ 15:00 UTC

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Go version
        run: go version

      - name: Run test suite
        run: make vet lint coverage

      - name: Upload test coverage
        uses: coverallsapp/github-action@v2
        with:
          file: coverprofile.out
          format: golang
